editor:
  config:
    importModules:
      - '@creifenscheid/cke-textpartlanguage/plugin.js'

    toolbar:
      items:
        - textPartLanguage
    language:
      textPartLanguage:
        # EXAMPLE - {title: 'arabic', languageCode: 'ar', textDirection: 'rtl'}
        - { title: 'english', languageCode: 'en' }